import { expect } from 'e2e'
import { readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { test } from '../dsh.js'
import { addWorkspace, createInstance, deleteDialog, detailField, inspectNode, openWorkflows } from '../ui.js'

test('Bash 自动启动一次、手动失败重试、严格输出校验与重启不重跑', async ({ app, screen, browser, dsh }) => {
  await app.open('/')
  await addWorkspace(screen, dsh.workspace)
  await createInstance(screen, dsh.workspaceName, 'regression-bash', 'bash-regression')
  await inspectNode(screen, 'automatic')
  await expect(detailField(browser, 'automatic', '状态')).toHaveText('已完成')
  expect(JSON.parse((await detailField(browser, 'automatic', '输出').textContent())!)).toEqual({ text: 'hello from upstream' })
  expect(await readFile(join(dsh.workspace, 'automatic-runs.txt'), 'utf8')).toBe('auto\n')

  await inspectNode(screen, 'retry')
  const retry = screen.getByRole('complementary', '详情 retry', { exact: true })
  expect(JSON.parse((await detailField(browser, 'retry', '输入').textContent())!)).toEqual({ text: 'hello from upstream' })
  await retry.getByRole('button', '执行', { exact: true }).tap()
  await expect(detailField(browser, 'retry', '状态')).toHaveText('执行异常')
  await expect(retry).toContainText('Command exited with code 7')
  await expect(retry).toContainText('first attempt failed')
  expect(await readFile(join(dsh.workspace, 'attempts.txt'), 'utf8')).toBe('attempt\n')
  await inspectNode(screen, 'finish')
  await expect(detailField(browser, 'finish', '状态')).toHaveText('等待')

  await inspectNode(screen, 'retry')
  await retry.getByRole('button', '执行', { exact: true }).tap()
  await expect(browser.locator('aside[aria-label="详情 retry"] section[aria-label="运行信息"] strong:text-is("输出") + pre')).toHaveText('{"result":42}')
  await expect(detailField(browser, 'retry', '状态')).toHaveText('执行异常')
  await expect(retry.getByRole('alert').first()).toHaveText('INVALID_FIELD_TYPE')
  await expect(detailField(browser, 'retry', '输出')).toHaveCount(0)
  expect(await readFile(join(dsh.workspace, 'attempts.txt'), 'utf8')).toBe('attempt\nattempt\n')
  await inspectNode(screen, 'finish')
  await expect(detailField(browser, 'finish', '状态')).toHaveText('等待')

  await inspectNode(screen, 'retry')
  await retry.getByRole('button', '执行', { exact: true }).tap()
  await expect(detailField(browser, 'retry', '状态')).toHaveText('已完成')
  expect(JSON.parse((await detailField(browser, 'retry', '输出').textContent())!)).toEqual({ result: 'hello from upstream' })
  await expect(retry.getByRole('button', '执行', { exact: true })).toHaveCount(0)
  await inspectNode(screen, 'finish')
  await expect(detailField(browser, 'finish', '状态')).toHaveText('就绪')
  expect(JSON.parse((await detailField(browser, 'finish', '输入').textContent())!)).toEqual({ result: 'hello from upstream' })
  await screen.getByRole('complementary', '详情 finish', { exact: true }).getByRole('button', '执行', { exact: true }).tap()
  await expect(detailField(browser, 'finish', '状态')).toHaveText('已完成')

  await dsh.restart(browser)
  await app.open('/')
  await openWorkflows(screen, browser)
  await screen.getByRole('button', /^bash-regression/).tap()
  await inspectNode(screen, 'retry')
  await expect(detailField(browser, 'retry', '状态')).toHaveText('已完成')
  expect(JSON.parse((await detailField(browser, 'retry', '输出').textContent())!)).toEqual({ result: 'hello from upstream' })
  expect(await readFile(join(dsh.workspace, 'automatic-runs.txt'), 'utf8')).toBe('auto\n')
  expect(await readFile(join(dsh.workspace, 'attempts.txt'), 'utf8')).toBe('attempt\nattempt\nattempt\n')
})

test('Bash 执行中禁止重复操作与删除，结束后允许删除', async ({ app, screen, browser, dsh }) => {
  await app.open('/')
  await addWorkspace(screen, dsh.workspace)
  await createInstance(screen, dsh.workspaceName, 'regression-gate', 'running-regression')
  await inspectNode(screen, 'gate')
  await expect(detailField(browser, 'gate', '状态')).toHaveText('运行中')
  await expect(screen.getByRole('complementary', '详情 gate', { exact: true }).getByRole('button', '执行', { exact: true })).toHaveCount(0)
  const confirm = await deleteDialog(screen, 'running-regression')
  await confirm.getByRole('button', '删除实例', { exact: true }).tap()
  await expect(confirm.getByRole('alert')).toContainText('命令仍在执行，暂不能删除实例。')
  await confirm.getByRole('button', '取消', { exact: true }).tap()
  await screen.getByRole('tab', 'running-regression', { exact: true }).tap()
  await expect.poll(() => readFile(join(dsh.workspace, 'gate-runs.txt'), 'utf8')).toBe('start\n')
  await writeFile(join(dsh.workspace, 'release.txt'), '')
  await expect(detailField(browser, 'gate', '状态')).toHaveText('已完成')
  expect(await readFile(join(dsh.workspace, 'gate-runs.txt'), 'utf8')).toBe('start\n')
  const finished = await deleteDialog(screen, 'running-regression')
  await finished.getByRole('button', '删除实例', { exact: true }).tap()
  await expect(screen.getByRole('button', /^running-regression/)).toHaveCount(0)
})

test('Bash 宿主中断后显示结果未知，不自动重跑，由用户明确重试', async ({ app, screen, browser, dsh }) => {
  await app.open('/')
  await addWorkspace(screen, dsh.workspace)
  await createInstance(screen, dsh.workspaceName, 'regression-gate', 'unknown-regression')
  await inspectNode(screen, 'gate')
  await expect(detailField(browser, 'gate', '状态')).toHaveText('运行中')
  await expect.poll(() => readFile(join(dsh.workspace, 'gate-runs.txt'), 'utf8')).toBe('start\n')
  await dsh.stop()
  await writeFile(join(dsh.workspace, 'release.txt'), '')
  await dsh.start()
  await dsh.authenticate(browser)
  await app.open('/')
  await openWorkflows(screen, browser)
  await screen.getByRole('button', /^unknown-regression/).tap()
  await inspectNode(screen, 'gate')
  await expect(detailField(browser, 'gate', '状态')).toHaveText('结果未知')
  await expect(screen.getByRole('complementary', '详情 gate', { exact: true })).toContainText('上次执行结果未知')
  expect(await readFile(join(dsh.workspace, 'gate-runs.txt'), 'utf8')).toBe('start\n')
  await screen.getByRole('complementary', '详情 gate', { exact: true }).getByRole('button', '执行', { exact: true }).tap()
  await expect(detailField(browser, 'gate', '状态')).toHaveText('已完成')
  expect(await readFile(join(dsh.workspace, 'gate-runs.txt'), 'utf8')).toBe('start\nstart\n')
})
