import { expect } from 'e2e'
import { access, readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { test } from '../dsh.js'
import { addWorkspace, createInstance, detailField, inspectNode, openWorkflows } from '../ui.js'

test('条件边按真实布尔结果激活，关闭分支跳过且汇合继续接收结果', async ({ app, screen, browser, dsh }) => {
  await app.open('/')
  await addWorkspace(screen, dsh.workspace)
  await createInstance(screen, dsh.workspaceName, 'regression-branches', 'branches-regression')
  await inspectNode(screen, 'source')
  await screen.getByRole('complementary', '详情 source', { exact: true }).getByRole('button', '执行', { exact: true }).tap()
  await expect(detailField(browser, 'source', '状态')).toHaveText('已完成')
  await inspectNode(screen, 'closed')
  await expect(detailField(browser, 'closed', '状态')).toHaveText('已跳过')
  await expect(screen.getByRole('complementary', '详情 closed', { exact: true }).getByRole('button', '执行', { exact: true })).toHaveCount(0)
  await inspectNode(screen, 'active')
  await expect(detailField(browser, 'active', '状态')).toHaveText('就绪')
  await screen.getByRole('complementary', '详情 active', { exact: true }).getByRole('button', '执行', { exact: true }).tap()
  await expect(detailField(browser, 'active', '状态')).toHaveText('已完成')
  await inspectNode(screen, 'join')
  await expect(detailField(browser, 'join', '状态')).toHaveText('就绪')
  expect(JSON.parse((await detailField(browser, 'join', '输入').textContent())!)).toEqual({ answer: 'active result' })
  await screen.getByRole('complementary', '详情 join', { exact: true }).getByRole('button', '执行', { exact: true }).tap()
  await expect(detailField(browser, 'join', '状态')).toHaveText('已完成')
  expect(await access(join(dsh.workspace, 'closed-runs.txt')).then(() => true, () => false)).toBe(false)
  await screen.getByRole('button', '根 DAG 详情', { exact: true }).tap()
  await expect(detailField(browser, 'regression-branches', '状态')).toHaveText('已完成')
})

test('for 项身份独立，部分完成后重启只恢复未完成项并按源顺序聚合', async ({ app, screen, browser, dsh }) => {
  await app.open('/')
  await addWorkspace(screen, dsh.workspace)
  await createInstance(screen, dsh.workspaceName, 'regression-loop', 'loop-regression')
  await inspectNode(screen, 'source')
  await screen.getByRole('complementary', '详情 source', { exact: true }).getByRole('button', '执行', { exact: true }).tap()
  await expect(detailField(browser, 'source', '状态')).toHaveText('已完成')
  await inspectNode(screen, 'each b')
  expect(JSON.parse((await detailField(browser, 'each', '输入').textContent())!)).toEqual({ title: 'Beta' })
  expect(JSON.parse((await detailField(browser, 'each', '逐项身份').textContent())!)).toEqual({ key: 'b', index: 1 })
  const secondId = await detailField(browser, 'each', '节点实例').textContent()
  await screen.getByRole('complementary', '详情 each', { exact: true }).getByRole('button', '执行', { exact: true }).tap()
  await expect(detailField(browser, 'each', '状态')).toHaveText('已完成')
  await inspectNode(screen, 'each a')
  const firstId = await detailField(browser, 'each', '节点实例').textContent()
  expect(firstId).not.toBe(secondId)
  await expect(detailField(browser, 'each', '状态')).toHaveText('就绪')
  await inspectNode(screen, 'finish')
  await expect(detailField(browser, 'finish', '状态')).toHaveText('等待')

  await dsh.restart(browser)
  await app.open('/')
  await openWorkflows(screen, browser)
  await screen.getByRole('button', /^loop-regression/).tap()
  await inspectNode(screen, 'each b')
  await expect(detailField(browser, 'each', '节点实例')).toHaveText(secondId!)
  await expect(detailField(browser, 'each', '状态')).toHaveText('已完成')
  expect(JSON.parse((await detailField(browser, 'each', '输出').textContent())!)).toEqual({ done: 'Beta' })
  await inspectNode(screen, 'each a')
  await expect(detailField(browser, 'each', '节点实例')).toHaveText(firstId!)
  await expect(detailField(browser, 'each', '状态')).toHaveText('就绪')
  await screen.getByRole('complementary', '详情 each', { exact: true }).getByRole('button', '执行', { exact: true }).tap()
  await expect(detailField(browser, 'each', '状态')).toHaveText('已完成')
  await inspectNode(screen, 'finish')
  await expect(detailField(browser, 'finish', '状态')).toHaveText('就绪')
  expect(JSON.parse((await detailField(browser, 'finish', '输入').textContent())!)).toEqual({ done: ['Alpha', 'Beta'] })
  expect(await readFile(join(dsh.workspace, 'each-runs.txt'), 'utf8')).toBe('Beta\nAlpha\n')
  await screen.getByRole('complementary', '详情 finish', { exact: true }).getByRole('button', '执行', { exact: true }).tap()
  await expect(detailField(browser, 'finish', '状态')).toHaveText('已完成')
  await screen.getByRole('button', '根 DAG 详情', { exact: true }).tap()
  await expect(detailField(browser, 'regression-loop', '状态')).toHaveText('已完成')
})

test('for 空数组不生成虚构项，下游跳过且根 DAG 完成', async ({ app, screen, browser, dsh }) => {
  await writeFile(join(dsh.workspace, 'empty.txt'), '')
  await app.open('/')
  await addWorkspace(screen, dsh.workspace)
  await createInstance(screen, dsh.workspaceName, 'regression-loop', 'empty-loop-regression')
  await inspectNode(screen, 'source')
  await screen.getByRole('complementary', '详情 source', { exact: true }).getByRole('button', '执行', { exact: true }).tap()
  await expect(detailField(browser, 'source', '状态')).toHaveText('已完成')
  expect(JSON.parse((await detailField(browser, 'source', '输出').textContent())!)).toEqual({ jobs: [] })
  await inspectNode(screen, 'each')
  await expect(detailField(browser, 'each', '状态')).toHaveText('已跳过')
  await expect(detailField(browser, 'each', '节点实例')).toHaveCount(0)
  await expect(screen.getByRole('button', /^详情 each /)).toHaveCount(0)
  await inspectNode(screen, 'finish')
  await expect(detailField(browser, 'finish', '状态')).toHaveText('已跳过')
  expect(await access(join(dsh.workspace, 'each-runs.txt')).then(() => true, () => false)).toBe(false)
  await screen.getByRole('button', '根 DAG 详情', { exact: true }).tap()
  await expect(detailField(browser, 'regression-loop', '状态')).toHaveText('已完成')
})
