import { expect } from 'e2e'
import { test } from '../dsh.js'
import { addWorkspace, createInstance, deleteDialog, detailField, inspectNode } from '../ui.js'

test('session_agent 跨实例关联准确、对话往返不完成、重启复用与人工完成后仍可返回', async ({ app, screen, browser, dsh }) => {
  await app.open('/')
  await addWorkspace(screen, dsh.workspace)
  await createInstance(screen, dsh.workspaceName, 'regression-session', 'session-first')
  await inspectNode(screen, 'task')
  const task = screen.getByRole('complementary', '详情 task', { exact: true })
  await task.getByRole('button', '执行', { exact: true }).tap()
  await expect(task.getByRole('button', '完成', { exact: true })).toBeEnabled()
  await task.getByRole('button', '打开对话', { exact: true }).tap()
  await expect(screen.getByRole('button', '返回实例', { exact: true })).toBeEnabled()
  // dsh keeps navigation off the URL; the selected sidebar row identifies the conversation.
  const firstConversation = await browser.locator('[role="treeitem"][aria-selected="true"][data-row-key^="session:"]').getAttribute('data-row-key')
  expect(firstConversation).toBeTruthy()
  await expect(screen.getByRole('button', '复制', { exact: true })).toHaveCount(1)
  await screen.getByRole('button', '返回实例', { exact: true }).tap()
  await expect(screen.getByRole('heading', 'session-first', { exact: true })).toBeVisible()
  await expect(detailField(browser, 'task', '状态')).toHaveText('就绪')
  await inspectNode(screen, 'after')
  await expect(detailField(browser, 'after', '状态')).toHaveText('等待')

  await createInstance(screen, dsh.workspaceName, 'regression-session', 'session-second')
  await inspectNode(screen, 'task')
  await task.getByRole('button', '执行', { exact: true }).tap()
  await expect(task.getByRole('button', '完成', { exact: true })).toBeEnabled()
  await task.getByRole('button', '打开对话', { exact: true }).tap()
  await expect(screen.getByRole('button', '返回实例', { exact: true })).toBeEnabled()
  const secondConversation = await browser.locator('[role="treeitem"][aria-selected="true"][data-row-key^="session:"]').getAttribute('data-row-key')
  expect(secondConversation).toBeTruthy()
  expect(secondConversation).not.toBe(firstConversation)
  await screen.getByRole('button', '返回实例', { exact: true }).tap()
  await expect(screen.getByRole('heading', 'session-second', { exact: true })).toBeVisible()
  await expect(screen.getByRole('tab', 'session-first', { exact: true })).toHaveCount(1)
  await expect(screen.getByRole('tab', 'session-second', { exact: true })).toHaveCount(1)
  await task.getByRole('button', '打开对话', { exact: true }).tap()
  await expect(browser.locator(`[data-row-key="${secondConversation}"]`)).toHaveAttribute('aria-selected', 'true')
  await expect(browser.locator('[role="treeitem"][data-row-key^="session:"]')).toHaveCount(2)
  await expect(screen.getByRole('button', '复制', { exact: true })).toHaveCount(1)

  await dsh.restart(browser)
  await app.open('/')
  await expect(browser.locator('[role="treeitem"][aria-selected="true"]')).toBeVisible()
  await browser.locator(`[data-row-key="${firstConversation}"]`).tap()
  await expect(screen.getByRole('button', '返回实例', { exact: true })).toBeEnabled()
  await screen.getByRole('button', '返回实例', { exact: true }).tap()
  await expect(screen.getByRole('heading', 'session-first', { exact: true })).toBeVisible()
  await expect(detailField(browser, 'task', '状态')).toHaveText('就绪')
  await browser.locator(`[data-row-key="${secondConversation}"]`).tap()
  await expect(screen.getByRole('button', '返回实例', { exact: true })).toBeEnabled()
  await screen.getByRole('button', '返回实例', { exact: true }).tap()
  await expect(screen.getByRole('heading', 'session-second', { exact: true })).toBeVisible()
  await expect(detailField(browser, 'task', '状态')).toHaveText('就绪')
  await task.getByRole('button', '打开对话', { exact: true }).tap()
  await expect(browser.locator(`[data-row-key="${secondConversation}"]`)).toHaveAttribute('aria-selected', 'true')
  await expect(browser.locator('[role="treeitem"][data-row-key^="session:"]')).toHaveCount(2)
  await expect(screen.getByRole('button', '复制', { exact: true })).toHaveCount(1)
  await screen.getByRole('button', '返回实例', { exact: true }).tap()
  await task.getByRole('button', '完成', { exact: true }).tap()
  await expect(detailField(browser, 'task', '状态')).toHaveText('已完成')
  expect(JSON.parse((await detailField(browser, 'task', '输出').textContent())!)).toEqual({})
  await expect(task.getByRole('button', '完成', { exact: true })).toHaveCount(0)
  await task.getByRole('button', '打开对话', { exact: true }).tap()
  await expect(browser.locator(`[data-row-key="${secondConversation}"]`)).toHaveAttribute('aria-selected', 'true')
  await screen.getByRole('button', '返回实例', { exact: true }).tap()
  await expect(detailField(browser, 'task', '状态')).toHaveText('已完成')
  await inspectNode(screen, 'after')
  await expect(detailField(browser, 'after', '状态')).toHaveText('就绪')

  const confirm = await deleteDialog(screen, 'session-second')
  await confirm.getByRole('button', '删除实例', { exact: true }).tap()
  await expect(screen.getByRole('tab', 'session-second', { exact: true })).toHaveCount(0)
  await browser.locator(`[data-row-key="${secondConversation}"]`).tap()
  await expect(screen.getByRole('navigation', '会话层级', { exact: true })).toBeVisible()
  await expect(screen.getByRole('button', '返回实例', { exact: true })).toHaveCount(0)
  await expect(browser.locator('[role="treeitem"][data-row-key^="session:"]')).toHaveCount(2)
})
